In [6]:
grades = [85, 92, 76, 92, 100, 76, 85, 92]
grades_set=set(grades)
print(f"Benzersiz liste set ile düzeltildi: {grades_set}")
print(f"En yüksek not: {max(grades)} \nEn düşük not: {min(grades)} ")
print(f"Notlarin küçükten büyüğe siralanmis hali : {sorted(grades) }")


Benzersiz liste set ile düzeltildi: {100, 92, 85, 76}
En yüksek not: 100 
En düşük not: 76 
Notlarin küçükten büyüğe siralanmis hali : [76, 76, 85, 85, 92, 92, 92, 100]


In [8]:
def armstrong_num(num):
    basamak_sayisi = len(str(num))
    toplam = sum(int(b)**basamak_sayisi for b in str(num))
    if toplam == num:
        print(f"{num} bir Armstrong sayısıdır.")
    else:
        print(f"{num} bir Armstrong sayısı değildir.")



number=int(input("Bir sayi yaziniz Armstrong sayısı olup olmadığını kontrol edelim:  "))
armstrong_num(number)


Bir sayi yaziniz Armstrong sayısı olup olmadığını kontrol edelim:   545


545 bir Armstrong sayısı değildir.


In [9]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
print(f"Ortak diller: {A.intersection(B)}")
print(f"Sadece A’da olan dilleri listeyelim: {A.difference(B)}")
print(f"İki kümenin birleşimini alfabetik olarak yazdiralim: {sorted(A.union(B))} ")



Ortak diller: {'SQL', 'Python'}
Sadece A’da olan dilleri listeyelim: {'R', 'Java'}
İki kümenin birleşimini alfabetik olarak yazdiralim: ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL'] 


In [12]:
import random
import statistics

numList = random.choices(range(1, 101), k=10)
print("Rastgele Sayilar:", numList)


ortalama = statistics.mean(numList)
std_sapma = statistics.stdev(numList)

print(f"Ortalama: {ortalama:.2f}")
print(f"Standart Sapma: {std_sapma:.2f}")


Rastgele Sayilar: [97, 42, 3, 74, 88, 28, 80, 99, 82, 48]
Ortalama: 64.10
Standart Sapma: 32.19


In [13]:
from collections import Counter


def kelime_sayacı(text):
    
    cleanText = ''.join(char if char.isalnum() or char.isspace() else ' ' for char in metin)
    
    
    words = cleanText.split()
    
   
    countWords = len(words)
    
    
    long = max(words, key=len)
    
    
    sayac = Counter(words)
    most = sayac.most_common(1)[0][0]
    
    return countWords, long, most

metin = "Python çok güçlü bir dil. Python ile veri analizi, yapay zeka ve daha fazlası yapılabilir!"
words, long, most = kelime_sayacı(metin)

print(f"Toplam kelime sayısı: {words}")
print(f"En uzun kelime: {long}")
print(f"En sık geçen kelime: {most}")


Toplam kelime sayısı: 15
En uzun kelime: yapılabilir
En sık geçen kelime: Python


In [14]:
sayilar = [5, 12, 7, 18, 24, 3, 16]
print(f"Çift sayilar : {list(filter( lambda x : x % 2==0,sayilar))} ")
ciftSayilar=list(filter( lambda x : x % 2==0,sayilar))
print(f"Çift sayilarin kareleri : {list(map( lambda x : x **2,ciftSayilar))} ")
print(f"Çift sayilarin karelerinin azalan şekilde siralanmasi : {sorted(list(map( lambda x : x **2,ciftSayilar)),reverse=True)} ")

Çift sayilar : [12, 18, 24, 16] 
Çift sayilarin kareleri : [144, 324, 576, 256] 
Çift sayilarin karelerinin azalan şekilde siralanmasi : [576, 324, 256, 144] 


In [15]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
print(f"Her kelimenin uzunluğuna göre küçükten büyüğe sıralanasi: { sorted(kelimeler,key=lambda x : len(x))}")


Her kelimenin uzunluğuna göre küçükten büyüğe sıralanasi: ['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [16]:
import re
def sumNum(text):
    cleanText = re.findall(r'\d+', text)
    return sum(map(int,cleanText))

text=input("Karışık kelimeler ve rakamlar yazın toplayalim:")
print(f"Toplam :{sumNum(text)}")

Karışık kelimeler ve rakamlar yazın toplayalim: 545sxdsd545


Toplam :1090


In [20]:
import random
import numpy as np
numArr=np.random.randint(0,51,size=10)
print(f"Dizinin ortalamasi: {numArr.mean()}")
print(f"Standart sapmasını: {numArr.std()}")
print(f"En büyük değerini: {numArr.max()}")


Dizinin ortalamasi: 27.9
Standart sapmasını: 15.559241626763177
En büyük değerini: 50


In [21]:
import numpy as np
matris = np.random.rand(5, 5)
print("Orijinal Matris:\n", matris)
print(f"Her sütunun ortalamasını bulun: {np.mean(matris,axis=0)}")

binary_matris = (matris > 0.5).astype(int)
print("\nBinary Matris:\n", binary_matris)





Orijinal Matris:
 [[0.08045167 0.71380191 0.63336213 0.23420322 0.0962887 ]
 [0.12102661 0.45864404 0.33980355 0.83525146 0.19089174]
 [0.66839271 0.0314839  0.09190203 0.24588486 0.59960698]
 [0.55012239 0.19751985 0.3636408  0.39043847 0.46979095]
 [0.59253907 0.09573435 0.10742281 0.17266433 0.56539772]]
Her sütunun ortalamasını bulun: [0.40250649 0.29943681 0.30722626 0.37568847 0.38439522]

Binary Matris:
 [[0 1 1 0 0]
 [0 0 0 1 0]
 [1 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 1]]


In [22]:
kitaplar = [
{"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},
{"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil":
2020},
{"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},
{"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},
{"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},
{"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500,
"yil": 2021},
{"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}
]

In [23]:

import numpy as np
#en çok satan kitabi döndüren fonk
#en çok satan kitabi döndüren fonk
def en_cok_satan(kitaplar):
    en_cok_satan_kitap = None
    maksimum_satis = -1

    for kitap in kitaplar:
        if kitap["satis"] > maksimum_satis:
            maksimum_satis = kitap["satis"]
            en_cok_satan_kitap = kitap
    return en_cok_satan_kitap

print(en_cok_satan(kitaplar))

    
#yazarlarin toplam satişini döndüren fonk

def yazar_satislari(kitaplar):
    satislar = {}
    for kitap in kitaplar:
        yazar = kitap["yazar"]
        satis = kitap["satis"]
        if yazar in satislar:
            satislar[yazar] += satis
        else:
            satislar[yazar] = satis
    return satislar

print(yazar_satislari(kitaplar))
    

{'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}
{'Ali': 3400, 'Ayşe': 1550, 'Can': 1800, 'Deniz': 400}


In [24]:
def kitap_turleri(kitaplar):
    turler = {}
    for kitap in kitaplar:
        tur = kitap["tur"]
        if tur in turler:
            turler[tur] += 1
        else:
            turler[tur] = 1
    return turler
genre=kitap_turleri(kitaplar)
print("Kitap Türleri ve sayilari ",genre)

def kitapAdediFiltrele(kitaplar):
  filtList=[]
  for kitap in kitaplar:
    if kitap["satis"]>1000:
      filtList.append(kitap["isim"])
  return filtList

print(f"Satış adedi 1000’den fazla olan kitapların isimlerini bir listede toplayalim: {kitapAdediFiltrele(kitaplar)}")

Kitap Türleri ve sayilari  {'Bilim': 3, 'Akademik': 2, 'Sanat': 1, 'Sosyal': 1}
Satış adedi 1000’den fazla olan kitapların isimlerini bir listede toplayalim: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme']


In [25]:
sonrasi2020 = list(filter(lambda k: k["yil"] > 2020, kitaplar))
print("2020 sonrası çıkan kitaplar:")
for k in sonrasi2020:
    print("-", k["isim"])

satis_artis = list(map(lambda k: {**k, "satis": int(k["satis"] * 1.10)}, kitaplar))
print("\nSatış adedi %10 artırılmış kitaplar:")
for k in satis_artis:
    print("-", k["isim"], ":", k["satis"])

sirali = sorted(kitaplar, key=lambda k: k["satis"], reverse=True)
print("\nSatış miktarına göre azalan sıralama:")
for k in sirali:
    print("-", k["isim"], ":", k["satis"])
    
    


2020 sonrası çıkan kitaplar:
- Veri Bilimi 101
- Makine Öğrenmesi
- Matematiksel Modelleme
- Bilgi Toplumu

Satış adedi %10 artırılmış kitaplar:
- Veri Bilimi 101 : 1320
- Python ile Yapay Zeka : 1045
- İstatistik Temelleri : 770
- Makine Öğrenmesi : 1980
- Veri Görselleştirme : 440
- Matematiksel Modelleme : 1650
- Bilgi Toplumu : 660

Satış miktarına göre azalan sıralama:
- Makine Öğrenmesi : 1800
- Matematiksel Modelleme : 1500
- Veri Bilimi 101 : 1200
- Python ile Yapay Zeka : 950
- İstatistik Temelleri : 700
- Bilgi Toplumu : 600
- Veri Görselleştirme : 400


In [26]:
import statistics

# --- Ortalama satış adedi ---
satislar = [k["satis"] for k in kitaplar]
ortalama = statistics.mean(satislar)

# --- En çok satış yapan tür ---
tur_satis = {}
for k in kitaplar:
    tur_satis[k["tur"]] = tur_satis.get(k["tur"], 0) + k["satis"]
en_cok_tur = max(tur_satis, key=tur_satis.get)

# --- Standart sapma ---
std_sapma = statistics.stdev(satislar)

print("Ortalama satış adedi:", ortalama)
print("En çok satış yapan tür:", en_cok_tur, "(", tur_satis[en_cok_tur], "satış )")
print("Satışların standart sapması:", round(std_sapma, 2))


Ortalama satış adedi: 1021.4285714285714
En çok satış yapan tür: Bilim ( 3950 satış )
Satışların standart sapması: 506.51


In [27]:
import random
import statistics

# --- 1. Veriyi %70 eğitim, %30 test olarak ayır ---
train_size = int(len(kitaplar) * 0.7)
train_set = random.sample(kitaplar, train_size)  # eğitim verisi
test_set = [k for k in kitaplar if k not in train_set]  # geri kalan test verisi

print("Eğitim seti kitapları:", [k["isim"] for k in train_set])
print("Test seti kitapları:", [k["isim"] for k in test_set])

# --- 2. Eğitim verisinden yazarların ortalama satışını hesapla ---
yazar_satis = {}
for k in train_set:
    if k["yazar"] not in yazar_satis:
        yazar_satis[k["yazar"]] = []
    yazar_satis[k["yazar"]].append(k["satis"])

yazar_ortalama = {y: statistics.mean(satis) for y, satis in yazar_satis.items()}
print("\nEğitim verisindeki yazarların ortalama satışları:")
for y, ort in yazar_ortalama.items():
    print("-", y, ":", round(ort, 2))

# --- 3. Test verisinde ortalamanın üstünde satış yapanları bul ---
print("\nTest setinde ortalamanın üzerinde satan kitaplar:")
for k in test_set:
    yazar = k["yazar"]
    if yazar in yazar_ortalama and k["satis"] > yazar_ortalama[yazar]:
        print("-", k["isim"], "(", k["yazar"], ",", k["satis"], ")")


Eğitim seti kitapları: ['Veri Görselleştirme', 'Veri Bilimi 101', 'Bilgi Toplumu', 'İstatistik Temelleri']
Test seti kitapları: ['Python ile Yapay Zeka', 'Makine Öğrenmesi', 'Matematiksel Modelleme']

Eğitim verisindeki yazarların ortalama satışları:
- Deniz : 400
- Ali : 950
- Ayşe : 600

Test setinde ortalamanın üzerinde satan kitaplar:
- Python ile Yapay Zeka ( Ayşe , 950 )
- Matematiksel Modelleme ( Ali , 1500 )
